application: [PROJECTID]
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /rest/work/save
  script: restapisave.application

- url: /rest/work/get
  script: restapiget.application

- url: /rest/work/delete
  script: restapidelete.application

- url: /rest/user/create
  script: restapicreate.application

- url: /rest/settings/update
  script: restapisettings.application

- url: /rest/settings/get
  script: restapisettings.application

- url: /admin
  script: administration.application
  login: admin

- url: /static/assets
  static_dir: assets

- url: /.*
  script: default.application

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
